name: Build

on:
  push:
    branches:
  pull_request:
    branches:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Example
        run: echo "This was a triumph"
