name: Firmware Build

on:
  push:
    branches:
  pull_request:
    branches:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

        - uses: actions/cache@v3
          with:
            path: |
              ~/esp-idf
              ~/.espressif

      - name: Install ESP-IDF
        run: |
          git clone --recursive -b release/v5.1 https://github.com/espressif/esp-idf.git ~/esp-idf
          ~/esp-idf/install.sh esp32

      - name: Build Sensor Firmware
        run: |
          . ~/esp-idf/export.sh
          espsecure.py generate_signing_key --version 1 --scheme ecdsa256 firmware/sensor/secure_boot_signing_key.pem
          idf.py --project-dir firmware/sensor build

      - name: Build Camera Firmware
        run: echo TODO
