name: OTA Patch Build

on:
  push:
    branch:
      - 'ota-patch-generations'
    # branch:
      # - 'master'
    # tags:
      # - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        tag: ['v1.0', 'v1.1', 'v1.2'] # TODO: get these from job output which queries github

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          path: ${{ github.ref_name}}

      - uses: actions/checkout@v3
        with:
          ref: ${{ matrix.tag }}
          submodules: 'recursive'
          path: ${{ matrix.tag }}

      - uses: actions/cache@v3
        with:
          path: |
            ~/esp-idf
            ~/.espressif
            ~/builds
          key: ${{runner.os}}-idf

      - name: Install ESP-IDF
        run: |
            [ -d ~/esp-idf ] || git clone --recursive -b release/v5.1 https://github.com/espressif/esp-idf.git ~/esp-idf
            ~/esp-idf/install.sh esp32

            # TODO: use secret key
      - name: Build Sensor Firmware
        run: |
          . ~/esp-idf/export.sh
          espsecure.py generate_signing_key --version 1 --scheme ecdsa256 firmware/sensor/secure_boot_signing_key.pem
          [ -d ~/builds/${{ github.ref_name }} ] || idf.py --project-dir ${{ github.ref_name }}/firmware/sensor --build-dir ~/builds/${{ github.ref_name}}/sensor build
          [ -d ~/builds/${{ matrix.tag }} ]      || idf.py --project-dir ${{ matrix.tag }}/firmware/sensor      --build-dir ~/builds/${{ matrix.tag }}/sensor     build

          # TODO: publish somehow
      - name: Generate OTA Patches
        run: |
          pip install detools
          sensor_sha=$(sha256sum --binary builds/${{ matrix.tag }}/sensor/sensor.elf | head --bytes=16 | tac -rs ..)
          camera_sha=$(sha256sum --binary builds/${{ matrix.tag }}/camera/camera.elf | head --bytes=16 | tac -rs ..)
          servo_sha=$(sha256sum --binary builds/${{ matrix.tag }}/servo/servo.elf | head --bytes=16 | tac -rs ..)
          detools create_patch -c crle builds/${{ matrix.tag }}/sensor/sensor.bin builds/${{ github.ref_name }}/sensor/sensor.bin builds/sensor.${{ github.ref_name }}.patch
          detools create_patch -c crle builds/${{ matrix.tag }}/camera/camera.bin builds/${{ github.ref_name }}/camera/camera.bin builds/camera.${{ github.ref_name }}.patch
          detools create_patch -c crle builds/${{ matrix.tag }}/servo/servo.bin builds/${{ github.ref_name }}/servo/servo.bin builds/servo.${{ github.ref_name }}.patch
